; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ArkZ LineLabel"
#define MyAppVersion "260830"
#define MyAppPublisher "Ark-Z Arquitetura"
#define MyAppURL "https://arkz.duckdns.org"
#define MyAppExeName "ArkZLineLabel_v.260830_Setup"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{24081A5C-6906-4CD6-A2F9-96A652170C94}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\PROGRAMACAO\ARK-Z PLUGINS\ArkZLineLabel\Output
OutputBaseFilename={#MyAppExeName}
SetupIconFile=D:\PROGRAMACAO\ARK-Z PLUGINS\ArkZLineLabel\Fonts\Contents\Resources\Ark-Z.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardImageFile=D:\PROGRAMACAO\ARK-Z MENU (metrico)\INSTALA\Arquivos\Inno Setup\ArkZ_large.bmp
WizardSmallImageFile=D:\PROGRAMACAO\ARK-Z MENU (metrico)\INSTALA\Arquivos\Inno Setup\ArkZ_small.bmp
UninstallDisplayIcon={autopf}\Autodesk\ApplicationPlugins\ArkZLineLabel.bundle\Contents\Resources\ark-z.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Files]
Source: "D:\PROGRAMACAO\ARK-Z PLUGINS\ArkZLineLabel\Fonts\*"; DestDir: "{autopf}\Autodesk\ApplicationPlugins\ArkZLineLabel.bundle\"; Flags: ignoreversion recursesubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
Type: files; Name: "{app}\Support\ArkZLineLabel.cuix"
Type: files; Name: "{app}\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{app}\Support\ArkZLineLabel.mnr"
Type: files; Name: "{app}\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2013 - English\R19.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2013 - English\R19.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2013 - English\R19.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2013 - English\R19.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2014\R19.1\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2014\R19.1\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2014\R19.1\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2014\R19.1\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2015\R20.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2015\R20.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2015\R20.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2015\R20.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2016\R20.1\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2016\R20.1\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2016\R20.1\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2016\R20.1\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2017\R21.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2017\R21.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2017\R21.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2017\R21.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2018\R22.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2018\R22.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2018\R22.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2018\R22.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2019\R23.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2019\R23.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2019\R23.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2019\R23.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2020\R23.1\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2020\R23.1\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2020\R23.1\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2020\R23.1\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2021\R24.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2021\R24.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2021\R24.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2021\R24.0\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2022\R24.1\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2022\R24.1\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2022\R24.1\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2022\R24.1\enu\Support\ArkZLineLabel_light.mnr"
;
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2023\R24.2\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2023\R24.2\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2023\R24.2\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2023\R24.2\enu\Support\ArkZLineLabel_light.mnr"

Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2024\R24.3\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2024\R24.3\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2024\R24.3\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2024\R24.3\enu\Support\ArkZLineLabel_light.mnr"

Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2025\R25.0\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2025\R25.0\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2025\R25.0\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2025\R25.0\enu\Support\ArkZLineLabel_light.mnr"

Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2026\R25.1\enu\Support\ArkZLineLabel.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2026\R25.1\enu\Support\ArkZLineLabel.bak.cuix"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2026\R25.1\enu\Support\ArkZLineLabel.mnr"
Type: files; Name: "{userappdata}\Autodesk\AutoCAD 2026\R25.1\enu\Support\ArkZLineLabel_light.mnr"

;
